source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.8'

gem 'aws-sdk-sqs'
gem 'shoryuken'
gem 'geocoder'
gem 'rubocop', '~> 0.89.1', require: false
