version: "3"

services:
  db:
   image: "mysql:5.7"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USERNAME: root
     MYSQL_PASSWORD: root
   volumes:
      - my-datavolume:/var/lib/mysql 
   ports:
      - "3307:3306"
  api:
   depends_on:
      - "db"
   build:
    context: .      
    dockerfile: ./Dockerfile
   ports:
      - "3000:3000"
   environment:
     DB_USERNAME: root
     DB_PASSWORD: root
     DB_PORT: 3306
     DB_HOST: db
     RAILS_ENV: development
     ORDER_SERVICE_DATABASE_PASSWORD: 123456
     RAILS_MAX_THREADS: 5
   volumes:
      - ".:/app"
      - "./config/database.yml:/app/config/database.yml"

volumes:
  db:
  my-datavolume: